services:
    db:
        image: mysql
        restart: no
        ports:
            - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: no
        ports:
            - ${PHPMYADMIN_LOCAL_PORT}:${PHPMYADMIN_DOCKER_PORT}
        environment:
            PMA_ARBITRARY: 1
